/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-Binary_Decoder
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_BINARY_DECODER_API_H
#define INCLUDED_BINARY_DECODER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_Binary_Decoder_EXPORTS
#define BINARY_DECODER_API __GR_ATTR_EXPORT
#else
#define BINARY_DECODER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_BINARY_DECODER_API_H */
