# -*- coding: utf-8 -*-

"""

Created on Wed Jun 24 20:16:58 2026


@author: kesch
Filtering code generated by https://fiiir.com/
"""


import numpy as np
from collections import defaultdict
from gnuradio import gr
import pmt
import scipy.signal as signal

class wsprd_time_synced_block(gr.sync_block):
    def __init__(self, sample_rate=10000, signalCenterFrequency = 1000, maxRecordLength = 60, filterOnly = 1):
        gr.sync_block.__init__(
            self,
            name='Morse Code Decoder',
            in_sig=[np.complex64],
            out_sig=[np.complex64]
        )
        self.sample_rate = sample_rate
        self.signalCenterFreq = signalCenterFrequency
        self.dotTimeArr = []
        self.samples_to_record = int(maxRecordLength* self.sample_rate)
        self.bits = []
        self.deci = round(self.sample_rate/10)
        self.d_count = self.deci
        self.ninputItems = 0 
        self.finalList = []
        self.filterOnly = filterOnly
        self.textOutput = ''
        self.dotTime = 0
        self.highDurCounter = 0
        self.lowDurCounter = 0
        self.dashTime = 100
        self.state = 0
        self.morseDic = {'13': 'A', '3111': 'B', '3131': 'C', '311': 'D', '1': 'E', '1131': 'F', '331': 'G', '1111': 'H', '11': 'I', '1333': 'J', '313': 'K', '1311': 'L', '33': 'M', '31': 'N', '333': 'O', '1331': 'P', '3313': 'Q', '131': 'R', '111': 'S', '3': 'T', '113': 'U', '1113': 'V', '133': 'W', '3113': 'X', '3133': 'Y', '3311': 'Z', '13333': '1', '11333': '2', '311113': '3', '11113': '4', '11111': '5', '31111': '6', '33111': '7', '33311': '8', '33331': '9', '33333': '0', '331133': ', ', '131313': '.', '113311': '?', '31131': '/', '31331': '(', '313313': ')', '7': ' ', '313137' : 'Start of Message -\n', '731313' : ' \n- End of message\n' }
        
        fL = self.signalCenterFreq - 1000     # Lower cutoff frequency
        fH = self.signalCenterFreq + 1000     # Upper cutoff frequency
        NL = 433      # Filter length for roll-off at fL (must be odd)
        NH = 433      # Filter length for roll-off at fH (must be odd)
        beta = 6.755  # Kaiser window beta
        # Low-pass filter setup
        hlpf = np.sinc(2 * fH / self.sample_rate * (np.arange(NH) - (NH - 1) / 2))
        hlpf *= np.kaiser(NH, beta)
        hlpf /= np.sum(hlpf)
        
        # High-pass filter setup
        hhpf = np.sinc(2 * fL / self.sample_rate * (np.arange(NL) - (NL - 1) / 2))
        hhpf *= np.kaiser(NL, beta)
        hhpf /= np.sum(hhpf)
        hhpf = -hhpf
        hhpf[(NL - 1) // 2] += 1
        
        # Final Band-pass coefficients
        if fL < 0: 
            fL = 0
            self.h = hlpf
        else:
            self.h = np.convolve(hlpf, hhpf)
        self.filter_state = np.zeros(len(self.h) - 1, dtype=np.complex64)

        
    def work(self, input_items, output_items):
        in0 = input_items[0]
        out_data = output_items[0]
        filtered_in0, self.filter_state = signal.lfilter(self.h, 1, in0, zi=self.filter_state)
        n = len(filtered_in0)
        out_data [:n] = filtered_in0
        ni = 0 
        self.finalList = []
        self.textOutput = ''
        if self.ninputItems <= self.samples_to_record and self.state == 0:
            while ni < n: 
                self.d_count -= 1 
                if self.d_count <= 0: 
                    power = abs(filtered_in0[ni])**2
                    if power >= 0.004: 
                        self.bits.append(1)
                        self.highDurCounter += 1
                        self.lowDurCounter  = 0
                    else: 
                        if self.highDurCounter > 0: 
                            self.dotTimeArr.append(self.highDurCounter)
                            if len(self.dotTimeArr) == 1 and self.filterOnly !=1: 
                                print("Message Recive Started...")
                        self.highDurCounter = 0
                        self.lowDurCounter += 1
                        self.bits.append(0)
                        if len(self.dotTimeArr) >= 5 and self.lowDurCounter >= self.dashTime*4: 
                            self.state = 1
                    self.d_count = self.deci
                    if len(self.dotTimeArr) >=5: 
                        # Calculate adaptive thresholds based on the actual recorded signal
                        sortedTimeArr = sorted(self.dotTimeArr)
                        self.dotTime = sortedTimeArr[0]
                        self.dashTime = sortedTimeArr[-1]
                ni += 1
                self.ninputItems += 1
            return n
        else: 
            if len(self.dotTimeArr) == 0:
                print("No Morse pulses recorded.")
                return -1  # Stop the flowgraph
            # Midpoints to separate noisy states
            active_midpoint = (self.dotTime + self.dashTime) / 2.0
            space_midpoint_char = (self.dotTime + self.dashTime) / 2.0
            space_midpoint_word = (self.dashTime + (7 * self.dotTime)) / 2.0
            
            try:
                # Strip leading zeros to align the start of the message
                start_index = self.bits.index(1)
                self.bits = self.bits[start_index:]
            except ValueError:
                print("No active signals found in recording.")
                return -1
            
            rle = []
            current_state = self.bits[0]
            current_len = 1
            for bit in self.bits[1:]:
                if bit == current_state:
                    current_len += 1
                else:
                    rle.append((current_state, current_len))
                    current_state = bit
                    current_len = 1
            rle.append((current_state, current_len))
            
            # Classify the RLE blocks using adaptive midpoints
            for state, length in rle:
                if state == 1:  # Active pulse (1s)
                    if length < active_midpoint:
                        self.finalList.append('1')  # Dot
                    else:
                        self.finalList.append('3')  # Dash
                else:  # Silent gap (0s)
                    if length < space_midpoint_char:
                        # Inter-element space (ignored, it just separates elements inside a letter)
                        pass
                    elif length < space_midpoint_word:
                        self.finalList.append('0')  # Character space
                    else:
                        self.finalList.append('7')  # Word space
            lastIndex = 0
            startMessage = 0
            for curIndex in range(len(self.finalList)): 
                if self.finalList[curIndex] == '7':
                    t = "".join(self.finalList[lastIndex:curIndex])
                    if t == "31313":  
                        if startMessage == 0: 
                            t = t + "7"
                            startMessage = 1
                        else: 
                            t = '7' + t 
                            startMessage = 0 
                    if t: 
                        if t in self.morseDic:
                            self.textOutput = self.textOutput + self.morseDic[t] + ' '
                        else: 
                            print(f"Warning: Unknown Morse sequence '{t}' at word boundary.")
                            self.textOutput = self.textOutput + '[?]'
                    lastIndex = curIndex + 1
                if self.finalList[curIndex] == '0': 
                    t = "".join(self.finalList[lastIndex:curIndex])
                    if t: 
                        if t in self.morseDic:
                            self.textOutput = self.textOutput + self.morseDic[t] 
                        else:
                            print(f"Warning: Unknown Morse sequence '{t}' at character boundary.")
                            self.textOutput = self.textOutput + '[?]'
                    lastIndex = curIndex + 1
            if self.filterOnly == 0: 
                print(self.textOutput) 
            self.ninputItems = 0 
            self.bits = []
            self.dotTime = 0
            self.dotTimeArr = []
            self.spaceTime = 0 
            self.state = 0
            return n

