/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-Morse_Encoder
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_MORSE_ENCODER_API_H
#define INCLUDED_MORSE_ENCODER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_Morse_Encoder_EXPORTS
#define MORSE_ENCODER_API __GR_ATTR_EXPORT
#else
#define MORSE_ENCODER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_MORSE_ENCODER_API_H */
